//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasiTodo.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVEGUARD
    {
        public int actgCodigo { get; set; }
        public string actgSerial { get; set; }
        public string actgCuenta { get; set; }
        public int puesCodigo { get; set; }
        public string actgNumero { get; set; }
        public int operCodigo { get; set; }
        public string actgBateria { get; set; }
        public string actgDescripcion { get; set; }
    
        public virtual PUESTO PUESTO { get; set; }
        public virtual OPERADOR OPERADOR { get; set; }
    }
}
