//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasiTodo.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVETRACK
    {
        public int acttCodigo { get; set; }
        public string acttSerial { get; set; }
        public string acttCuenta { get; set; }
        public string acttNombre { get; set; }
        public string acttUbicacion { get; set; }
        public string acttNumero { get; set; }
        public int operCodigo { get; set; }
        public string acttBateria { get; set; }
        public string acttDescripcion { get; set; }
    
        public virtual OPERADOR OPERADOR { get; set; }
    }
}
