//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasiTodo.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPUTADOR
    {
        public int compCodigo { get; set; }
        public string compSerial { get; set; }
        public int marcCodigo { get; set; }
        public string compModelo { get; set; }
        public string compColor { get; set; }
        public int sisoCodigo { get; set; }
        public int puesCodigo { get; set; }
    
        public virtual MARCA MARCA { get; set; }
        public virtual SISTEMAOPERATIVO SISTEMAOPERATIVO { get; set; }
        public virtual PUESTO PUESTO { get; set; }
    }
}
