//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasiTodo.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUARDA
    {
        public int guarCodigo { get; set; }
        public string guarIdentificacion { get; set; }
        public string guarNombre { get; set; }
        public string guarCelular { get; set; }
        public string guarDireccion { get; set; }
        public string guarBarrio { get; set; }
        public string guarMoto { get; set; }
        public int ciudCodigo { get; set; }
    
        public virtual CIUDAD CIUDAD { get; set; }
    }
}
