//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasiTodo.Logica.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUESTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PUESTO()
        {
            this.ACTIVEGUARD = new HashSet<ACTIVEGUARD>();
            this.COMPUTADOR = new HashSet<COMPUTADOR>();
        }
    
        public int puesCodigo { get; set; }
        public string puesIoc { get; set; }
        public string puesNombre { get; set; }
        public int ciudCodigo { get; set; }
        public string puesDireccion { get; set; }
        public string puesBarrio { get; set; }
        public string puesTelefono { get; set; }
        public string puesExtencion { get; set; }
        public int zonaCodigo { get; set; }
        public int ejecCodigo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVEGUARD> ACTIVEGUARD { get; set; }
        public virtual CIUDAD CIUDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPUTADOR> COMPUTADOR { get; set; }
        public virtual EJECUTIVO EJECUTIVO { get; set; }
        public virtual ZONA ZONA { get; set; }
    }
}
